### PR TITLE
Fixes #64 - Ability to pass context to Create method

### LINKED ISSUE #64: Ability to pass context to `Create` method
`Create` should accept context and pass the same to `exec.CommandContext`.
It'd be very useful in cancelling the PDF generation requests with the context cancellation signal.

### PR DESCRIPTION
**Pull request by ArsalanKhairani**
Updated test cases and added test for context cancellation

### CODE REVIEW

**Comment by SebastiaanKlippert** [comment]
Hi, nice job and good addition, CommandContext did not exist when I first created this.
But what's your opinion on creating a `CreateContext` method instead of changing the signature of Create?
That way we cna avoid a breaking change and program that use contexts are not forced to use empty contexts.

**Comment by SebastiaanKlippert** [comment]
Cool, looks better. Thanks.

Do the tests pass on your machine?
Travis is failing https://travis-ci.org/github/SebastiaanKlippert/go-wkhtmltopdf/jobs/767909057 
Might be because wkhtmltopdf is using stderr and signal:killed is somewhere at the end of the buffer, you could try inspecting it using SetStderr or use the quiet option? 
Did not have time to look myself on my machines. If you find anything you are welcome to fix, if not I will take a look tomorrow and then merge it.

**Comment by ArsalanKhairani** [comment]
Yes, it did pass on my machine. However, looks like If `wkhtmltopdf` process gets started before the timeout, error contains the logs and not signal:killed error. I've added `stderr` to get the actual error and matched that.

I am thinking, should we do the following in the following instead (in run method)?
```
        // run cmd to create the PDF
	err := cmd.Run()
	if err != nil {
		if ctxErr := ctx.Err(); ctxErr != nil {
			return ctxErr
		}

		// on an error, return the contents of Stderr if it was our own buffer
		// if Stderr was set to a custom writer, just return err
		...
	}
```

**Comment by SebastiaanKlippert** [comment]
Good job.
The ctxErr looks interesting. Agree that is probably is better to return that error first because the other error is would not be relevant.
I think you can inlcude that if you want to, then I will test it later.

**Comment by SebastiaanKlippert** [comment]
Thanks, looks like a clean change now!

**Pull request merged**
