### PR TITLE
Update travis config to use latest wkhtmltopdf RC

### PR DESCRIPTION
**Pull request by jacobhaven**
We needed to do this to avoid this issue: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001 based on @ashkulz suggestion.

### CODE REVIEW

**Comment by SebastiaanKlippert** [comment]
Thanks for the quick update!

**Comment by ashkulz** [comment]
Please note that the rc builds will be removed from the current location after the funal release (which will be hosted at Github).

**Comment by SebastiaanKlippert** [comment]
Thanks for the reminder @ashkulz 
I will update after the latest release.

**Comment by ashkulz** [comment]
0.12.5 has been released and `-rc` builds have been removed, please take updated URL from https://wkhtmltopdf.org/downloads.html#stable

**Comment by SebastiaanKlippert** [comment]
Thanks, been looking at your releases and waiting for the builds

**Pull request merged**
